name = "some-styles"
description = "A theme inspired by no-styles-please (and some others) with slightly heavier CSS."
# An optional tags to allow quick search
tags = []
license = "MIT"
homepage = "https://github.com/it-is-final/some-styles"
# The minimum version of Zola required
min_version = "0.20.0"
# An optional live demo URL
demo = "https://it-is-final.github.io/some-styles/"

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]

# The theme author info: you!
[author]
name = "Luong Truong (final)"
homepage = "https://it-is-final.github.io"
